name: anivel
type: web
env:
  APP_NAME: "AniVel"
  ADMIN_KEY: "dhdouh08"
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: "base64:xBfe/FMAhapeXsCmtSV2a19A3q78b21CMOPU6Gro89Y="
  APP_URL: "https://${{ app.name }}.koyeb.app"
  LOG_CHANNEL: stderr
  LOG_LEVEL: debug
  DB_CONNECTION: sqlite
  DB_DATABASE: /var/www/html/database/database.sqlite
  SESSION_DRIVER: database
  CACHE_STORE: database
  QUEUE_CONNECTION: database
  FILESYSTEM_DISK: local
  VITE_APP_NAME: "AniVel"
build:
  type: dockerfile
run:
  cmd: apache2-foreground
