name: anivel
type: web
env:
  APP_NAME: "AniVel"
  APP_ENV: production
  APP_DEBUG: false
  APP_KEY: "base64:xBfe/FMAhapeXsCmtSV2a19A3q78b21CMOPU6Gro89Y="
  APP_URL: "https://${{ app.name }}.koyeb.app"
  LOG_CHANNEL: stderr
  LOG_LEVEL: debug
  DB_CONNECTION: sqlite
  DB_DATABASE: /app/database/database.sqlite
  SESSION_DRIVER: database
  CACHE_STORE: database
  QUEUE_CONNECTION: database
  FILESYSTEM_DISK: local
  VITE_APP_NAME: "AniVel"
  ADMIN_KEY: "dhdouh08"
build:
  type: buildpack
  run:
    - composer install --no-dev --optimize-autoloader
    - npm install
    - npm run build
    - mkdir -p database
    - touch database/database.sqlite
    - chmod -R 775 storage bootstrap/cache database
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - php artisan migrate --force
run:
  cmd: php artisan serve --host=0.0.0.0 --port=$PORT
